title:  "H ♡ I"
tagline: "Alexander - Astiz Le Bras Wedding"
description: "The Wedding of Harriet Alexander and Isabela Astiz Le Bras"

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'H ♡ I'

menu:
- {name: 'Logistics', folder: 'pages', file: 'Logistics'}
- {name: 'Love', folder: 'pages', file: 'Love'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
# - {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
# - {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
# - {name: 'About', folder: 'pages', file: 'about.html'}
# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/halexand'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
